language: ruby
services:
- postgresql
before_install:
- cd SisGPWeb
- psql -c 'create database travis_ci_test;' -U postgres
script:
- bundle exec spring binstub --all
- bundle install
- bundle exec rake spec
rvm:
- 2.2.3
notifications:
  email:
    recipients:
    - dan.b412@gmail.com
    - rafael.akiyoshi@gmail.com
branches:
  only:
  - master
after_success:
- coveralls
deploy:
  api_key:
    secure: lKjX88IYDljqUq2DxirNRpT4I2QsyTb7ziNye8NjPsCYZOc+Pvz/0y3kXSd0pI7yKNxOzg1TvaUW6roaSwo275OoeBgZZG/Q81Gjb1i5pWRJOUPnGVW9v4As1OkGlGNL6Fkkj1XSpITBdPedjZPyv55hTTLT5/cGNSKtETOrrBGFfeGGLnPaU4KhBbzaBBkJn4dFRKHMmglDQEhCyPy/VzqbaoIr01smBZIo69NUcut8q8i3LaQ+QzYz1Lx28cuVBCSrkmHg/8/WQeq5pPcwQ0IQZjADV+F0xtaoqluSDiqIAfcn9n1jZinPHLIiWw/li52iuOa5L02+PqtGYKF3WcOCNwrChS54Hj4wFaK7U2NT5Z2SB8BghJRNwPQBYZuKdp7x+gL8HKkm1NCxk45Wd6xbvxlFCyDTU5Z7m1ENXQ22W6H15+SrXUBSws7zQZnqyLhJBXaBXWZ6EaogFLKeejLyVK2Zcc6h2RIjCY4fTzcutuL9tvb5pvM/jHyY+ssTObhmAyb31vldKO7l97tGL71xXtegz9odqNxKeaBR44APhQmVOCjcso58tNuS/Q7adCyymvnf34n1zR4dbEdHlyZhm1IWl/k4/SIg7XY8sqfoyc2cm3ehrpKtx5GDiuRPy6u9kaA5KX78ollktzefDLLjTuj9ingQ5j5uQtIkS6g=
