language: ruby

before_install: 
  cd SisGPWeb
  
script:
  - bundle exec spring binstub --all
  - bundle install
  - bundle exec rake db:drop
  - bundle exec rake db:migrate
  - bundle exec rake test

rvm:
  - 2.2.3
notifications:
  email:
    recipients:
      - marcowilliamdf@gmail.com
  
branches:
  only:

    - master

notifications:
  slack: sisgp:ZLP4zzYc0XwS6yN4F1HkLjQM
